# ----------------------------------------------------------------------------------
# GitHub Actions CI/CD: Spring PetClinic 빌드, 테스트, Docker 이미지 푸시 + GitOps 업데이트 (PAT 사용)
# ----------------------------------------------------------------------------------
name: PetClinic CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-docker-update-gitops:
    name: Build, Test, Docker Push, Update GitOps
    runs-on: ubuntu-24.04

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout application code
        uses: actions/checkout@v4

      # 2. Java (JDK 17) 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3. Maven 빌드 및 테스트
      - name: Build and Test PetClinic
        run: mvn clean install

      # 4. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker image
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/petclinic
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build -t $DOCKER_REPO:$IMAGE_TAG .
          
          echo "Pushing Docker image to Docker Hub: $DOCKER_REPO:$IMAGE_TAG"
          docker push $DOCKER_REPO:$IMAGE_TAG
          echo "Image pushed successfully to Docker Hub."

      # 6. GitOps Repository 업데이트 (Helm Chart values.yaml 이미지 태그 변경) - PAT 사용
      - name: Update GitOps repository with new image tag
        env:
          GITOPS_REPO_URL: "https://github.com/${{ github.repository_owner }}/gitops-repo.git"
          NEW_IMAGE_FULL_PATH: "${{ secrets.DOCKER_USERNAME }}/petclinic:${{ github.sha }}" # Docker Hub 사용 시
          GITOPS_REPO_PAT: ${{ secrets.GITOPS_REPO_PAT }}
        run: |
          echo "Cloning GitOps repository using PAT..."
          git clone https://${GITOPS_REPO_PAT}@github.com/${{ github.repository_owner }}/gitops-repo.git gitops-repo-local
          cd gitops-repo-local

          echo "Updating image tag in values.yaml..."
          sed -i "s|^\([[:space:]]*tag:\).*|\1 \"${{ github.sha }}\"|" petclinic-app/values.yaml

          # Docker Hub 사용 시 repository 경로 업데이트 (ECR 사용하는 경우는 다른 sed 명령)
          sed -i "s|^\([[:space:]]*repository:\).*|\1 \"${{ secrets.DOCKER_USERNAME }}/petclinic\"|" petclinic-app/values.yaml

          echo "Committing changes..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add petclinic-app/values.yaml
          git commit -m "chore(CD): Update PetClinic image tag to ${{ github.sha }}" || echo "No changes to commit"

          echo "Pushing changes to GitOps repository using PAT..."
          git push https://${GITOPS_REPO_PAT}@github.com/${{ github.repository_owner }}/gitops-repo.git main

