# ----------------------------------------------------------------------------------
# GitHub Actions CI/CD: Spring PetClinic 빌드, 테스트, Docker 이미지 푸시 + GitOps 업데이트 (PAT 사용)
# ----------------------------------------------------------------------------------
name: PetClinic CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-docker-update-gitops:
    name: Build, Test, Docker Push, Update GitOps
    runs-on: ubuntu-24.04

    env:
      # GitOps Helm values.yaml 경로
      GITOPS_REPO_PATH: petclinic-gitops-manifests/petclinic-app/values.yaml

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout application code
        uses: actions/checkout@v4

      # 2. Java (JDK 17) 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3. Maven 빌드 및 테스트
      - name: Build and Test PetClinic
        run: mvn clean install

      # 4. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker image
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/petclinic
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build -t $DOCKER_REPO:$IMAGE_TAG .
          
          echo "Pushing Docker image to Docker Hub: $DOCKER_REPO:$IMAGE_TAG"
          docker push $DOCKER_REPO:$IMAGE_TAG
          echo "Image pushed successfully to Docker Hub."

      # 6. GitOps Repository 업데이트 (Helm Chart values.yaml) - PAT 사용
      - name: Update GitOps Helm values.yaml
        env:
          GITOPS_REPO_PAT: ${{ secrets.GITOPS_REPO_PAT }}
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/petclinic
        run: |
          echo "Cloning GitOps repository using PAT..."
          git clone https://${GITOPS_REPO_PAT}@github.com/${{ github.repository_owner }}/gitops-repo.git gitops-repo-local
          cd gitops-repo-local

          echo "Installing yq for YAML editing..."
          sudo apt-get update && sudo apt-get install -y yq

          echo "Updating image tag and repository in values.yaml..."
          yq eval ".image.tag = strenv(IMAGE_TAG)" -i $GITOPS_REPO_PATH
          yq eval ".image.repository = strenv(DOCKER_REPO)" -i $GITOPS_REPO_PATH

          echo "Committing and pushing changes to GitOps repository..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $GITOPS_REPO_PATH
          git commit -m "chore(CD): Update PetClinic image tag to $IMAGE_TAG" || echo "No changes to commit"
          git push https://${GITOPS_REPO_PAT}@github.com/${{ github.repository_owner }}/gitops-repo.git main

